---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ramb

<!-- badges: start -->
<!-- badges: end -->

The goal of {ramb} is to return various "move"-objects to tibbles for further downstream processing using the tidyverse lingo.

## Installation

You can install the development version of {ramb} from [GitHub](https://github.com/einarhjorleifsson/ramb) with:

``` r
# install.packages("devtools")
devtools::install_github("einarhjorleifsson/ramb")
```

## Example

Basic example of workflow:

```{r example}
library(tidyverse)
library(ramb)
d <- 
  creel %>% 
  rename(ID = id) %>% 
  as.data.frame() %>% 
  moveHMM::prepData(type = "UTM", coordNames = c("x", "y")) %>% 
  filter(ID == 1) %>%
  filter(!is.na(step)) %>%
  # convert step length from meters to knots (nautical miles per hour)
  mutate(speed = step/ 60 * 1.9438)
mixtools::normalmixEM(d$speed, mu = c(1,4,8), sigma = c(1,1,1)) %>%
  tidy_normalmixEM() %>% 
  glimpse()
```

```{r}
o <-
  creel %>%
  filter(id == 1) %>%
  select(time, lon, lat, everything()) %>%
  as.data.frame() %>%
  EMbC::stbc(., info = -1)
o %>% 
  tidy_bin_clst_path() %>% 
  group_by(behaviour, A) %>% 
  summarise(p = n(),
            .groups = "drop") %>% 
  spread(A, p)
  ggplot(aes(speed, turn, colour = factor(A))) +
  geom_point()
library(ggnewscale)
o %>% 
  tidy_bin_clst_path() %>% 
  ggplot(aes(dTm)) +
  theme_bw() +
  geom_segment(aes(y = 0, xend = dTm, yend = max(speed), colour = behaviour),
               alpha = 0.5) +
  scale_colour_manual(values = c("hauling" = "#A6CEE3", 
                                 "shooting" = "#1F78B4",
                                 "steaming" = "grey")) +
  ggnewscale::new_scale_colour() +
  geom_point(aes(y = speed, colour = factor(A)),
             size = 0.5) +
  scale_colour_manual(values = c("1" = "#E31A1C",
                                 "2" = "blue",
                                 "3" = "blue",
                                 "4" = "blue"))





p2 <- 
  o %>% 
  tidy_bin_clst_path() %>% 
  ggplot(aes(dTm, max(turn), fill = behaviour)) +
  geom_col() +
  geom_point(aes(y = turn)) +
  scale_fill_brewer(palette = "Set1")
p3 <- 
  o %>% 
  tidy_bin_clst_path() %>% 
  ggplot(aes(dTm, max(speed), fill = factor(A))) +
  geom_col() +
  geom_point(aes(y = speed)) +
  scale_fill_brewer(palette = "Set1")
p4 <- 
  o %>% 
  tidy_bin_clst_path() %>% 
  ggplot(aes(dTm, max(turn), fill = factor(A))) +
  geom_col() +
  geom_point(aes(y = turn)) +
  scale_fill_brewer(palette = "Set1")


library(patchwork)
p1 + p3 + p2 + p4 + plot_layout(ncol = 1)

o %>% 
  tidy_bin_clst_path() %>% 
  ggplot(aes(dTm, max(turn), fill = factor(A))) +
  geom_col() +
  geom_point(aes(y = turn, colour = ))
```

