devtools::build_readme()
pkgdown::build_site()
#system("mkdir /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/ramb")
system("rm -rf  /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/ramb/*")
system("cp -r docs/* /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/ramb/.")
system("chmod -R a+rX /net/hafri.hafro.is/export/home/hafri/einarhj/public_html/pkg/ramb")
