---
title: "Basics"
date: "`r lubridate::now()`"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

```{r}
library(sf)
library(mapview)
library(mapdeck)
library(lubridate)
library(ramb)
library(tidyverse) # alway load this last (because of potential function name conflicts)
```

```{r, echo = FALSE}
fil <- "~/r/Pakkar2/ramb/TOPSECRET.R"
if(file.exists(fil)) source(fil) 
```

## Vessel in harbour (A point in polygon issue)

Example data: Icelandic survey tracks and some harbour polygons

```{r}
harbours <- 
  ramb::read_is_harbours() %>% 
  # filter out some smaller harbours, cause a nuisance downstream
  filter(!hid %in% c("HRI", "ASS", "HAU", "GRE", "MJH", "MJO", "AED", "HJA"))
```

```{r}
tracks <- 
  read_is_survey_tracks() %>% 
  mutate(speed = ifelse(speed > 12, 12, speed)) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE)
harbours <- 
  read_sf("ftp://ftp.hafro.is/pub/data/shapes/harbours.gpkg") %>% 
  filter(iso2a == "IS",
         !hid %in% c("HRI", "ASS", "HAU", "GRE", "MJH", "MJO", "AED", "HJA"))
```

```{r}
tracks <-
  tracks %>% 
  st_join(harbours) %>% 
  mutate(inharbour = ifelse(!is.na(hid), TRUE, FALSE))
```

```{r}
bb <- st_bbox(c(xmin = -22.75, ymin = 64.05, 
                xmax = -21.65, ymax = 64.20), 
              crs = 4326)

mapdeck(location = c(-22.0, 64.1), zoom = 9) %>% 
  add_polygon(data = harbours, fill_colour = "#FF000095", tooltip = "hid", update_view = FALSE) %>% 
  add_scatterplot(data = tracks %>% st_crop(bb) %>% arrange(inharbour), 
                  fill_colour  = "inharbour", radius = 100, update_view = FALSE)
```

## some other stuff

```{r}
track <-
  read_csv("https://raw.githubusercontent.com/ices-eg/WKSSFGEO/main/example_data_AIS.csv") %>% 
  # reduce typing in downstream code
  rename(vid = vessel_id, time = time_stamp) %>% 
  # unique rows
  distinct() %>% 
  # remove duplicate time
  distinct(vid, time, .keep_all = TRUE) %>% 
  # # remove same positions (this is not recommended could theoretically be possible
  # distinct(vid, lon, lat, .keep_all = TRUE)
  arrange(vid, time) %>% 
  group_by(vid) %>% 
  mutate(duration = difftime(time, lag(time), units = "hours"),
         # warnings here are just because of the first datapoint
         distance = geo::arcdist(lat, lon, lag(lat), lag(lon), scale = "nmi"),
         speed_derived = distance / as.numeric(duration))
```


```{r}
track %>% 
  sample_n(1e4) %>% 
  ggplot(aes(speed, speed_derived)) +
  geom_point(alpha = 0.01, size = 1) +
  geom_abline(colour = "red") +
  coord_equal()
```

