---
title: "Identifying vessel activity during a trawl survey"
date: "`r lubridate::now()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(mapdeck)
library(tidyverse)
library(lubridate)
```

```{r, echo = FALSE}
m <- 
  ramb::trawlsurvey %>% 
  rename(id = vid) %>% 
  mutate(rowid = 1,
         x = 0,
         y = 0) %>% 
  select(id, rowid, time, x, y, lon, lat, behaviour) %>% 
  ramb::rb_gaussian_binary_clustering()

d <- 
  bind_cols(ramb::trawlsurvey,
            m %>% ungroup() %>% select(spn:turn, speed2 = speed))
# count of runs
d2 <-
  d %>% 
  group_by(vid) %>% 
  mutate(run = ramb::rb_event(A)) %>%
  group_by(vid, run) %>% 
  mutate(n = n()) %>% 
  ungroup()
d2 %>% 
  count(A, behaviour, n) %>% 
  ggplot(aes(n, nn, colour = behaviour)) +
  geom_point() +
  facet_wrap(~ A)

d %>% 
  filter(speed2 < 12) %>% 
  ggplot(aes(speed2, turn, colour = factor(A))) +
  theme_bw() +
  geom_point(size = 0.5) +
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~ vid)
d %>% 
  ggplot(aes(speed, turn, colour = factor(A))) +
  theme_bw() +
  geom_point(size = 0.5) +
  scale_colour_brewer(palette = "Set1") +
  facet_wrap(~ vid)

d %>% 
  ggplot(aes(speed, fill = factor(A))) +
  theme_bw() +
  geom_histogram() +
  scale_fill_brewer(palette = "Set1")

d %>% 
  mutate(day = day(time)) %>% 
  filter(day == 9) %>% 
  ggplot(aes(time, speed, colour = factor(A))) +
  geom_point() +
  facet_grid(vid ~ behaviour)
d %>% 
  mutate(day = day(time)) %>% 
  filter(day == 9) %>% 
  ggplot(aes(time, speed2, colour = factor(A))) +
  geom_point() +
  facet_grid(vid ~ behaviour)
d %>% 
  count(behaviour, A) %>% 
  spread(A, n)
d %>% 
  count(behaviour, A) %>% 
  group_by(A) %>% 
  mutate(p = round(n / sum(n) * 100)) %>% 
  select(-n) %>% 
  spread(A, p)
```


```{r}
vessel.track <- 
  m %>% 
  sf::st_as_sf(coords = c("lon", "lat"),
               crs = 4326) %>% 
  group_by(id) %>% 
  summarise(do_union = FALSE) %>%
  sf::st_cast("LINESTRING")

mapdeck(location = c(-22.9, 66.15),
        zoom = 8) %>% 
  add_path(data = ramb::trawlsurveytows,
           layer_id = "tows",
           stroke_colour = "#AAFFFFFF",
           stroke_width = 1000,
           update_view = FALSE) %>% 
  mapdeck::add_path(data = vessel.track,
                          layer_id = "track",
                          stroke_width = 250,
                          width_min_pixels = 5,
                          width_max_pixels = 10,
                          tooltip = "id",
                          auto_highlight = TRUE,
                          highlight_colour = "#FF000095",
                          update_view = FALSE,
                          stroke_colour = "#E0FFFF80") %>% 
  add_scatterplot(data = d %>% mutate(A = as_factor(A)),
                  layer_id = "point",
                  lon = "lon", 
                  lat = "lat",
                  radius = 250,
                  fill_colour = "A",
                  tooltip = "A",
                  #palette = "inferno",
                  update_view = FALSE)
```




```{r, echo = FALSE, eval = FALSE}
library(tidyverse)
library(data.table)

#library(EMbC)
stk <-
  read_csv("ftp://ftp.hafro.is/pub/data/csv/is_smb_vms2019.csv") %>%
  select(vid, lon, lat, speed, heading, time) %>% 
  arrange(vid, time) %>% 
  drop_na(lon, lat) %>% 
  as.data.frame()
lgs <-
  read_csv("ftp://ftp.hafro.is/pub/data/csv/is_smb_stations.csv") %>%
  filter(year == 2019) %>%
  arrange(t1, t2) %>% 
  select(id.lgs = id, vid, lon.start = lon1, lat.start = lat1,
         lon.end = lon2, lat.end = lat2, start = t1, end = t2)
stk.dt <-
  stk %>%
  arrange(time) %>% 
  mutate(dummy = time) %>% 
  data.table()
lgs.dt <-
  lgs %>%
  arrange(start, end) %>%
  data.table()
setkey(stk.dt, vid, time, dummy)
setkey(lgs.dt, vid, start, end)
stk.lgs <- 
  foverlaps(stk.dt, lgs.dt, nomatch = NA) %>% 
  as.data.frame() %>% 
  mutate(behaviour = ifelse(!is.na(id.lgs), "hauling", "not hauling"))



glimpse(stk.lgs)
glimpse(stk)
d <- 
  stk.lgs %>% 
  select(ID = vid, time, lon, lat, speed, hauling) %>% 
  as_tibble()
d %>% 
  ggplot(aes(time, speed, colour = hauling)) +
  geom_point(size = 0.2) +
  facet_grid(ID ~ .)
library(lubridate)
d2 <- 
  d %>% 
  mutate(day = day(time)) %>% 
  filter(day %in% 4,
         ID %in% c(1277, 1281)) 

d2 %>% 
  ggplot(aes(time, speed, colour = hauling)) +
  geom_point(size = 0.2) +
  facet_grid(ID ~ .)

d3 <-
  moveHMM::prepData(as.data.frame(d2), 
                    type = "LL", 
                    coordNames = c("lon", "lat"))

EM_all <- mixtools::normalmixEM(d3$speed, mu = c(3.5, 10), sigma = c(1, 1))
plot(EM_all, density = TRUE, loglik = FALSE)



d %>% 
  group_by(ID) %>% 
  mutate(duration = difftime(lead(time), time, units = "mins"))





d %>% 
  ggplot(aes(speed, fill = hauling)) +
  geom_histogram()
d2 <-
  moveHMM::prepData(d, 
                    type = "LL", 
                    coordNames = c("lon", "lat")) 

EM_all <- mixtools::normalmixEM(d$speed, mu = c(3.5, 10), sigma = c(1, 1))
plot(EM_all, density = TRUE, loglik = FALSE)


# https://www.inpredictable.com/2021/06/analyzing-your-run-data-with-r.html
library(rpart)
stk.lgs %>% 
  select(vid, time, speed, lon, lat, hauling) %>% 
  as_tibble() %>% 
  filter(vid == 1277) ->
  d

rp <- 
  rpart(speed ~ time, data = d,
           control = rpart.control(cp = 0.005)) # adjust the cp parameter if the phases are over or under fit #
d$rpp <- predict(rp, d)
d %>% 
  ggplot(aes(time, speed)) +
  geom_point(aes(colour = hauling), size = 0.5) +
  geom_point(aes(y = rpp), colour = "cyan", size = 0.5) +
  scale_colour_brewer(palette = "Set1")
```

```{r, eval = FALSE}
# add intervals and labels to your run dataset #
rna <-
  d %>%
  group_by(rpp) %>%
  summarise(mnt=min(elt),mxt=max(elt),mnd=min(prd),mxd=max(prd)) %>%
  mutate(dst=mxd-mnd,avt=(mxt+mnt)/2) %>%
  mutate(gt=paste(format(dst,digits = 1)," miles @ ",format(rpp,digits=2)," mph",sep=""))


# https://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0158248
```

