---
title: "Basics"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(ferill)
d <- 
  creel %>% 
  moveHMM::prepData(type = "UTM", coordNames = c("x", "y")) %>% 
  filter(ID == "AR001") %>%
  filter(!is.na(step)) %>%
  # convert step length from meters to knots (nautical miles per hour)
  mutate(speed = step/ 60 * 1.9438)
mixtools::normalmixEM(d$speed, mu = c(1,4,8), sigma = c(1,1,1)) %>%
  tidy_normalmixEM() %>% 
  glimpse()
```

```{r}
d <-
  creel %>% 
  mutate(time = lubridate::ymd_hms(date)) %>%
  # use the prepData function to create step lengths
  moveHMM::prepData(type = "UTM", coordNames = c("x", "y")) %>%
  # check if there are any missing step lengths
  # there will be at least five (=the number of unique IDs) because the first step
  # length of each trip will be NA
  # remove missing step lengths
  filter(!is.na(step)) %>%
  # convert step length from meters to knots (nautical miles per hour)
  mutate(speed = step / 60 * 1.9438) %>%
  as_tibble() %>%
  sf::st_as_sf(coords = c("x", "y"),
               crs = '+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0',
               remove = FALSE) %>%
  sf::st_transform(crs = 4326) %>%
  mutate(lon = sf::st_coordinates(geometry)[,1],
         lat = sf::st_coordinates(geometry)[,2]) %>%
  sf::st_drop_geometry()
o <-
  d %>%
  filter(ID == "AR001") %>%
  select(time, lon, lat) %>%
  as.data.frame() %>%
  EMbC::stbc(., info = -1)
o %>% 
  tidy_bin_clst_path() %>% 
  glimpse()
```
