---
title: "Whacky points"
---

https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2656.13610

https://pratikunterwegs.github.io/atlastools/

https://nmml.github.io/tidy-movt-modeling/outlier-locs.html

https://github.com/pratikunterwegs/watlastools

```{r, include = FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE,
  collapse = TRUE,
  error = TRUE,
  comment = "#>"
)
```

## Premble

```{r}
#library(sftrack)
#library(trip)
library(ramb)
library(sf)
library(mapview)
library(traipse)
library(lubridate)
library(tidyverse)
library(patchwork)
library(argosfilter)
source("~/R/Pakkar2/ramb/TOPSECRET.R")
```

```{r}
whacks <- c(5, 10, 11, 15, 16, 17, 27:31)
w <-
  tibble(time = seq(ymd_hms("2022-10-15 00:00:00"),
                    ymd_hms("2022-10-15 01:00:00"),
                    by = "60 sec")) |> 
  mutate(vid = 1,      # vessel id
         tid = 1,      # trip id
         .rid = 1:n(), # unique number
         lat = seq(62, 62.2, length.out = max(.rid)),
         lon = -25,
         lon = ifelse(.rid %in% whacks, -24, lon),
         whacks = ifelse(.rid %in% whacks, TRUE, FALSE),
         lat = ifelse(.rid == 40, 62.04, lat),
         lon = ifelse(.rid == 40, -25.04, lon),
         whacks = ifelse(.rid == 40, TRUE, whacks),
         speed = ramb::rb_speed(lon, lat, time)) |> 
  select(vid, tid, .rid, lon, lat, time, speed, whacks)
p1 <- 
  w |> 
  ggplot(aes(lon, lat)) +
  geom_path() +
  geom_point(aes(colour = whacks), size = 0.5) +
  scale_colour_manual(values = c("FALSE" = "darkgreen", "TRUE" = "red"))
p2 <-
  w |> 
  ggplot(aes(time, speed)) +
  geom_line() +
  geom_point(aes(colour = whacks), size = 0.5) +
  scale_y_log10() +
  scale_colour_manual(values = c("FALSE" = "darkgreen", "TRUE" = "red"))

p1 + p2 + plot_layout(guides = "collect")
```

## Argos filter (vmask)

```{r}
w_argos <- 
  w |> 
  mutate(v = vmask(lat, lon, time, vmax = rb_kn2ms(15)))
p1 <- 
  w_argos |> 
  ggplot(aes(lon, lat)) +
  theme_bw() +
  geom_path() +
  geom_point(aes(colour = v), size = 1) +
  scale_colour_manual(values = c("end_location" = "darkgreen",
                                 "not" = "darkgreen",
                                 "removed" = "red"))
p1
```


```{r}
whacks <- c(5, 10, 11, 15, 16, 17, 27:31)
w <-
  tibble(time = seq(ymd_hms("2022-10-15 00:00:00"),
                    ymd_hms("2022-10-15 01:00:00"),
                    by = "60 sec")) |> 
  mutate(id = 1:n(),
         lat = seq(62, 62.2, length.out = max(id)),
         lon = -25,
         lon = ifelse(id %in% whacks, -24, lon),
         whacks = ifelse(id %in% whacks, TRUE, FALSE),
         lat = ifelse(id == 40, 62.04, lat),
         lon = ifelse(id == 40, -25.04, lon),
         whacks = ifelse(id == 40, TRUE, whacks)) |> 
  #slice(1:20) |> 
  mutate(id = 1) |> 
  select(lon, lat, time, id, whacks)
w |> 
  ggplot(aes(lon, lat)) +
  geom_path() +
  geom_point(aes(colour = whacks))
```

We can derive the speed as follows:

```{r}
w <-
  w |> 
  mutate(speed = traipse::track_speed(lon, lat, time) |> ramb::rb_ms2kn())
w |> 
  ggplot(aes(time, speed)) +
  geom_line() +
  geom_point(aes(colour = whacks)) +
  scale_y_log10()
```

We could try this (taniamendo):

```{r}
rb_lh <- function(df, speed_filter = 25) {
  org <- df
  repeat { 
    # here it is assumed that speed is already in place
    subset <-
      df %>%
      filter(speed > speed_filter)
    
    sel <- factor(subset$seq)
    
    nrows <- length(sel)
    
    if (nrows==0) {
      break
    } else {
      df <- df[!df$seq %in% sel,] 
    }
    
    df |> 
      group_by(device_id) |> 
      mutate(speed = traipse::track_speed(lon, lat, time) |> ramb::rb_ms2kn())
    
    if(FALSE) {
    df <-
      df%>%
      group_by(device_id)%>%
      mutate(dx=c(0, abs(diff(x_utm))),
             dy=c(0, abs(diff(y_utm))),
             dt=c(0, abs(diff(time_stamp))))
    
    df <-
      df %>%
      group_by(device_id)%>%
      mutate(dist = sqrt(dx^2 + dy^2),
             dt=c(0,abs(diff(time_stamp))))
    
    df$speed <- df$dist / df$dt * 1.943
    }
    
  }
  
  org |> 
    
  return(df)
  
}

```

```{r}
w |> 
  rename(device_id = id) |> 
  mutate(seq = 1:n()) |> 
  rb_lh() |> 
  ggplot(aes(lon, lat)) +
  geom_path() +
  geom_point(aes(colour = whacks))
```


```{r}
lh <- function(d) {
  tr <- d |> dplyr::select(lon, lat, time) |> mutate(id = 1)
  sp::coordinates(tr) <- ~lon+lat
  sp::proj4string(tr) <- sp::CRS("+proj=longlat +datum=WGS84", doCheckCRSArgs = FALSE)
  tr <- trip::trip(tr, c("time", "id"))
  d$.whacky <- !trip::speedfilter(tr, max.speed = ramb::rb_kn2ms(20) / 1000 * 60 * 60)
  return(d)
}
w |> 
  lh() |> 
  ggplot(aes(lon, lat)) +
  geom_path() +
  geom_point(aes(colour = .whacky))




d <- w |> select(-whacks)
trip(d)
sp::coordinates(d) <- ~lon+lat
sp::proj4string(d) <- sp::CRS("+proj=longlat +datum=WGS84", doCheckCRSArgs = FALSE)
tr <- trip(d, c("time", "id"))
w$whacky <- !speedfilter(tr, max.speed = ramb::rb_kn2ms(20) / 1000 * 60 * 60)
w
w |> rb_mapdeck(col = "whacky")
w |> 
  count(whacks, whacky)

w$whacky2 <- !sda(tr, smax = ramb::rb_kn2ms(20) / 1000 * 60 * 60, distlim = c(0.001, 1))
w
```

```{r}
PAM <- read_rds("~/stasi/gis/AIS_TRAIL/auxillary/PAM.rds")
con <- omar::connect_mar()
ais <- ramb::rb_read_trails(con, VID = 78, YEARS = 2009:2022, use_PAM = TRUE)

lh <- function(d) {
  tr <- d |> select(lon, lat, time) |> mutate(id = 1)
  sp::coordinates(tr) <- ~lon+lat
  sp::proj4string(tr) <- sp::CRS("+proj=longlat +datum=WGS84", doCheckCRSArgs = FALSE)
  tr <- trip(tr, c("time", "id"))
  d$.whacky <- !speedfilter(tr, max.speed = ramb::rb_kn2ms(20) / 1000 * 60 * 60)
}

ais2 <- 
  ais |> 
  lh()
ais2 |> mutate(year = year(time)) |> count(year, .whacky, .whacky2) |> spread(.whacky, n) |> 
  as.data.frame()
ais2 |> count(source, .whacky)
ais2 |> filter(year(time) == 2015) |> rb_mapdeck(col = ".whacky")
ais2 |> filter(source == "stk") |> rb_mapdeck(col = ".whacky")

ais2 |> filter(source == "stk", !.whacky) |> rb_mapdeck(col = "speed")


d <- ais |> mutate(id = 1) |> select(lon, lat, time, id)
#trip(d)
sp::coordinates(d) <- ~lon+lat
sp::proj4string(d) <- sp::CRS("+proj=longlat +datum=WGS84", doCheckCRSArgs = FALSE)
tr <- trip(d, c("time", "id"))
ais$whacky <- !speedfilter(tr, max.speed = ramb::rb_kn2ms(20) / 1000 * 60 * 60)
ais |> 
  count(whacky)
ais |> mutate(year = year(time)) |> count(year, whacky) |> spread(whacky, n)
ais |> 
  filter(year(time) == 2011) |> 
  #filter(!whacky) |> 
  rb_mapdeck(col = "whacky")
```







# OLDER BELOW

```{r}
knitr::opts_chunk$set(eval = FALSE)
```




```{r}
hb <- 
  read_is_harbours() %>%
  filter(iso2a == "IS",
         # filter out some smaller harbours, cause a nuisance downstream
         !hid %in% c("HRI", "ASS", "HAU", "GRE", "MJH", "MJO", "AED", "HJA")) %>% 
  mutate(hid = 1:n())
d <- 
  read_is_survey_tracks() %>% 
  mutate(.rid = 1:n(),
         year = year(time)) %>% 
  arrange(vid, time) %>% 
  select(.rid, everything()) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE) %>% 
  st_join(hb %>% select(hid)) %>% 
  st_drop_geometry() %>% 
  group_by(vid) %>% 
  mutate(pings = n(),
         whacky = ifelse(pings > 3, rb_whacky_speed(lon, lat, time), NA_real_)) %>% 
  ungroup() %>% 
  group_by(vid, whacky) %>% 
  mutate(inh = !is.na(hid),
         tid = rb_trip(inh)) %>% 
  ungroup()
d %>% 
  filter(!whacky) %>% 
  count(vid, tid) %>% 
  filter(tid > 0) %>% 
  spread(vid, n) %>% 
  knitr::kable()

d %>% 
  filter(!whacky,
         tid > 0) %>% 
  group_by(vid, tid) %>% 
  mutate(n = n()) %>% 
  ungroup() %>% 
  filter(n < 3) %>% 
  mutate(tid = paste(vid, tid)) %>% 
  rb_md_trip(tid)

```

```{r}
fil <- "https://raw.githubusercontent.com/ices-eg/WKSSFGEO/main/data/harbours.rds"
hbs <- read_rds(fil) %>% mutate(hid = 1:n())
fil <- "https://raw.githubusercontent.com/ices-eg/WKSSFGEO/main/data-examples/example_data_AIS.csv"
dat <- 
  readr::read_csv(fil) %>% 
  rename(vid = vessel_id,
         time = time_stamp) %>% 
  mutate(.rid = 1:n(),
         year = year(time)) %>% 
  arrange(vid, time) %>% 
  select(.rid, everything()) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE) %>% 
  st_join(hbs %>% select(hid)) %>% 
  st_drop_geometry() %>% 
  group_by(vid) %>% 
  mutate(pings = n(),
         whacky = ifelse(pings > 3, rb_whacky_speed(lon, lat, time), NA_real_)) %>% 
  ungroup() %>% 
  group_by(vid, whacky) %>% 
  mutate(inh = !is.na(hid),
         tid = rb_trip(inh)) %>% 
  ungroup()
dat %>% 
  count(vid, tid) %>% 
  spread(vid, n) %>% 
  knitr::kable()



d <- 
  d %>% 
  # point in harbour, each vessel will get a unique tid 
  #  within each year
  group_by(vid, year) %>% 
  dplyr::mutate(.gr0 = data.table::rleid( inh )) %>% 
  dplyr::group_by(vid, year, inh) %>% 
  dplyr::mutate(tid = data.table::rleid(.gr0)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(tid = ifelse(inh, -tid, tid)) %>% 
  dplyr::select(c(-.gr0, inh)) %>% 
  # check for wacky points
  group_by(vid, year, tid) %>% 
  mutate(pings = n(),
         sd = ifelse(pings > 3, track_distance(lon, lat), NA_real_),
         ss = ifelse(pings > 3, track_speed(lon, lat, time), NA_real_),
         st = track_time(time),
         duration = sum(st) / 60,      # duration in minutues
         whacky = ifelse(pings > 3, rb_whacky_speed(lon, lat, time), NA_real_)) %>% 
  ungroup()
```

```{r}
# whacky trips
d.whacky <- 
  d %>% 
  filter(tid > 0,
         whacky == 1) %>% 
  select(vid, year, tid) %>% 
  distinct() %>% 
  left_join(d)
d.whacky %>% 
  filter(lon < -10,
         lat > 62.5) %>% 
  ggplot(aes(lon, lat)) +
  geom_path(aes(group = paste(vid, year, tid))) +
  geom_point(data = d.whacky %>% filter(lon < -10, lat > 62.5) %>% arrange(whacky),
             aes(colour = factor(whacky)))
d.whacky %>% 
  filter(whacky == 0) %>% 
  mutate(tid = paste(vid, year, tid)) %>% 
  ggplot(aes(lon, lat)) +
  geom_path(aes(group = paste(vid, year, tid))) +
  geom_path(data = geo::island) +
  facet_wrap(~ tid)
# check out vid 2350, 2020-8
d.whacky %>% 
  filter(whacky == 0) %>% 
  mutate(tid = paste(vid, year, tid)) %>% 
  rb_md_trip(tid, radius = 500)
```

#### another check on whackies

```{r}
d2 <-
  d %>% 
  filter(tid > 0,
         whacky == 0,
         pings > 3) %>% 
  group_by(vid, year, tid) %>% 
  mutate(pings = n(),
         sd = ifelse(pings > 3, track_distance(lon, lat), NA_real_),
         ss = ifelse(pings > 3, track_speed(lon, lat, time), NA_real_),
         st = track_time(time),
         duration = sum(st, na.rm = TRUE) / 60,      # duration in minutues
         whacky = ifelse(pings > 3, rb_whacky_speed(lon, lat, time), NA_real_)) %>% 
  ungroup() 
d2 %>% 
  count(whacky)
d2 %>% 
  select(sd, ss, st) %>% 
  gather(var, val) %>% 
  ggplot(aes(val)) +
  geom_density() +
  facet_wrap(~ var, scales = "free")
# did not expect this
d2 %>% arrange(-ss)
d2 %>% filter(.rid %in% 84650:84670) %>% as.data.frame()
# here rectime may be the corred thing
```

```{r}
d2 %>% 
  filter(ss > rb_kn2ms(25))
d2 %>% 
  mutate(diff = as.numeric(difftime(rectime, time, units = "sec"))) %>% 
  mutate(diff = ifelse(diff < -5, -5, diff),
         diff = ifelse(diff >  60*10,  60*10, diff)) %>% 
  count(diff) %>% 
  filter(diff != 0) %>% 
  ggplot(aes(diff / 60, n)) +
  geom_point()
d2 %>% 
  mutate(diff = as.numeric(difftime(rectime, time, units = "sec"))) %>% 
  filter(diff >= 5 * 60) %>% 
  count(vid)
```


## older below



```{r}
d <- 
  read_is_survey_tracks() %>% 
  mutate(.rid = 1:n()) %>% 
  arrange(vid, time) %>% 
  select(.rid, everything()) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE) %>% 
  st_join(hb %>% select(hid)) %>% 
  st_drop_geometry() %>% 
  # here check for wacky points
  group_by(vid) %>% 
  mutate(pings = n(),
         sd = ifelse(pings > 3, track_distance(lon, lat), NA_real_),
         ss = ifelse(pings > 3, track_speed(lon, lat, time), NA_real_),
         st = track_time(time),
         duration = sum(st) / 60,      # duration in minutues
         whacky = rb_whacky_speed(lon, lat, time)) %>% 
  ungroup()

d2 <- 
  d %>% 
  # just a test, should not use filter here, loose info
  filter(!whacky) %>% 
  rb_define_trip(vid, hid) %>% 
  group_by(vid, tid) %>% 
  mutate(pings = n(),
         sd = ifelse(pings > 3, track_distance(lon, lat), NA_real_), 
         st = track_time(time),
         ss = ifelse(pings > 3, track_speed(lon, lat, time), NA_real_)) %>% 
  ungroup()
d2 %>% 
  count(vid, tid) %>% 
  filter(tid > 0) %>% 
  spread(vid, n) %>% 
  knitr::kable()
d2 %>% 
  filter(tid > 0) %>% 
  group_by(vid, tid) %>% 
  mutate(n = n()) %>% 
  filter(n < 5) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326) %>% 
  mapview::mapview()

d %>% 
  filter(.rid %in% 34409:34440) %>% 
  select(-c(rectime, heading, )) %>% 
  rename(cid = cruise_id) %>% 
  mutate(lon = round(lon, 3),
         lat = round(lat, 3),
         sd = round(sd),
         st = round(st / 60), # minutes
         ss = round(ss)) %>% 
  knitr::kable()

d %>% 
  filter(.rid %in% 34400:34440)  %>% 
  ggplot(aes(lon, lat)) +
  geom_path(data = geo::island, aes(lon, lat)) +
  geom_path() +
  geom_point(colour = "red")
d %>% 
  filter(.rid %in% 34400:34440) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326) %>% 
  mapview(zcol = "whacky")

d %>% 
  filter(.rid %in% 34433:34500)  %>% 
  ggplot(aes(lon, lat)) +
  geom_path(data = geo::island, aes(lon, lat)) +
  geom_path() +
  geom_point(colour = "red")

d2 %>% 
  filter(tid > 0,
         !is.na(st),
         !is.na(sd)) %>% 
  mutate(st = st / (60 * 60), 
         sd = sd / 1000,
         st = gisland::grade(st, 0.5),
         sd = gisland::grade(sd, 50)) %>% 
  count(sd, st) %>% 
  mutate(n = cut(n, breaks = c(0, 1, 2, 5, 10, 20, Inf))) %>% 
  ggplot() +
  geom_tile(aes(st, sd, fill = n)) +
  labs(x = "hours", y = "km") +
  scale_fill_viridis_d()
```

* whacky points are likely a combo of long distance over a short time step
* long time steps of days is likely a function of wrong trip definition, but time may also be suspect.


We could try to specify minimum duration for a trip

```{r}
d <- 
  read_is_survey_tracks() %>% 
  mutate(.rid = 1:n()) %>% 
  arrange(vid, time) %>% 
  select(.rid, everything()) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326,
           remove = FALSE) %>% 
  st_join(hb %>% select(hid)) %>% 
  st_drop_geometry() %>% 
  # here check for wacky points
  group_by(vid, cruise_id) %>% 
  mutate(sd = lead(track_distance(lon, lat)), 
         st = lead(track_time(time)),
         ss = lead(track_speed(lon, lat, time)),
         whacky = rb_whacky_speed(lon, lat, time)) %>% 
  ungroup() %>% 
  # just a test, should not use filter here, loose info
  #filter(!whacky) %>%
  dplyr::mutate(inharbour = ifelse(!is.na( hid ), TRUE, FALSE)) %>% 
  group_by(vid, cruise_id) %>% 
  dplyr::mutate(.gr0 = data.table::rleid( inharbour )) %>% 
  dplyr::group_by(vid, cruise_id, inharbour) %>% 
  dplyr::mutate(tid = data.table::rleid(.gr0)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(tid = ifelse(inharbour, -tid, tid)) %>% 
  dplyr::select(c(-.gr0, inharbour)) %>% 
  dplyr::group_by(vid, cruise_id, tid) %>% 
  dplyr::mutate(n.pings = n(),
                tid.duration = cumsum(st) / (60)) %>% 
  dplyr::ungroup()

d %>% filter(tid > 0) %>% mutate(year = year(time)) %>% count(vid, year, tid) %>% as.data.frame()

d %>% filter(tid > 0) %>% group_by(vid) %>% mutate(tid2 = rb_event(tid)) %>% 
  count(vid, tid) %>% 
  as.data.frame()
```

```{r}
d %>% 
  group_by(vid, tid) %>% 
  mutate(sd = ifelse(n.pings > 3, lead(track_distance(lon, lat)), NA), 
         st = lead(track_time(time)),
         ss = ifelse(n.pings > 3, lead(track_speed(lon, lat, time)), NA),
         whacky = ifelse(n.pings > 3, rb_whacky_speed(lon, lat, time), NA)) %>% 
  filter(n.pings %in% 3:20,
         tid > 0) %>% 
  arrange(n.pings, tid, time) %>% 
  st_as_sf(coords = c("lon", "lat"),
           crs = 4326) %>% 
  mutate(tid = as.character(tid)) %>% 
  mapview(zcol = "tid")

d10 <- 
  d %>% 
  group_by(vid, tid) %>% 
  mutate(sd = ifelse(n.pings > 3, lead(track_distance(lon, lat)), NA), 
         st = lead(track_time(time)),
         ss = ifelse(n.pings > 3, lead(track_speed(lon, lat, time)), NA),
         whacky = ifelse(n.pings > 3, rb_whacky_speed(lon, lat, time), NA))
d10 %>% 
  filter(n.pings %in% 3:50,
         tid > 0) %>% 
  mutate(tid = paste(vid, tid)) %>% 
  rb_md_trip(tid, radius = 250) %>% 
  mapdeck::add_polygon(hb, fill_opacity = 0.3)
```

```{r}
d %>% 
  filter(tid > 0) %>% 
  count(vid, tid) %>% 
  spread(vid, n) %>% 
  knitr::kable()
```


```{r}
s <- 
  d %>% 
  mutate(st = st / (60 * 60),
         sd = sd / 1000,
         ss = rb_ms2kn(ss)) %>% 
  gather(var, val, sd:ss) %>% 
  group_by(vid, cruise_id, var) %>% 
  summarise(q05 = quantile(val, 0.05, na.rm = TRUE),
            q50 = quantile(val, 0.50, na.rm = TRUE),
            q95 = quantile(val, 0.95, na.rm = TRUE),
            q99 = quantile(val, 0.99, na.rm = TRUE),
            max = max(val, na.rm = TRUE),
            .groups = "drop")
s %>% 
  ggplot(aes(max)) +
  geom_histogram() +
  facet_wrap(~ var, scales = "free")
```

```{r}
ex <- 
  tibble(.rid = 1:10,
         lat = seq(65, 65.2, length.out = 10),
         time = seq(ymd_hms("2021-12-04 01:00:00"),
                    ymd_hms("2021-12-04 02:00:00"),
                    length.out = 10)) %>% 
  mutate(lon = -24,
         lon = ifelse(.rid == 5, -26, lon),
         whacky = rb_whacky_speed(lon, lat, time),
         sa = rb_sa(lon, lat, time))

ex %>% 
  ggplot(aes(lon, lat, colour = whacky)) +
  geom_point(size = 10) +
  scale_colour_brewer(palette = "Set1")
ex %>% 
  ggplot(aes(lon, lat, colour = sa)) +
  geom_point(size = 10)
ex %>% 
  ggplot(aes(time, sa)) +
  geom_point() +
  geom_line()
```

