// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// whack_forward_cpp
LogicalVector whack_forward_cpp(NumericVector lon, NumericVector lat, NumericVector time, double ms_max, double max_gap_sec);
RcppExport SEXP _ramb_whack_forward_cpp(SEXP lonSEXP, SEXP latSEXP, SEXP timeSEXP, SEXP ms_maxSEXP, SEXP max_gap_secSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lon(lonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lat(latSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< double >::type ms_max(ms_maxSEXP);
    Rcpp::traits::input_parameter< double >::type max_gap_sec(max_gap_secSEXP);
    rcpp_result_gen = Rcpp::wrap(whack_forward_cpp(lon, lat, time, ms_max, max_gap_sec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ramb_whack_forward_cpp", (DL_FUNC) &_ramb_whack_forward_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_ramb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
