# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interpolate_track_cpp <- function(trk_code, trk_time, trk_vals, grp_start, x_code, x_time) {
    .Call(`_ramb_interpolate_track_cpp`, trk_code, trk_time, trk_vals, grp_start, x_code, x_time)
}

whack_forward_cpp <- function(lon, lat, time, ms_max, max_gap_sec) {
    .Call(`_ramb_whack_forward_cpp`, lon, lat, time, ms_max, max_gap_sec)
}

