#' Event id
#' 
#' 
#'
#' @param x A vector, normally character or integer
#'
#' @return A numerical vector that labels each discreet event
#' @export
#'
rb_number_runs <- function(x) {
  x <- dplyr::if_else(x != dplyr::lag(x), 1L, 0L, 1L)
  x <- cumsum(x)
  return(x)
}


#' rb_ms2kn
#'
#' meters per second to knots for those of us that forget the convertion number
#' 
#' @param x A numerical vector of speed in meters per second
#'
#' @return A vector, speed in knots (nautical miles per hour)
#' @noRd
#' 
#' @author Einar Hjörleifsson, \email{einar.hjorleifsson@gmail.com}
#'
.rb_ms2kn <- function(x) {
  x * 1.94384449
}

#' rb_kn2ms
#'
#' knots to meters per second for those of us that forget the convertion number
#' 
#' @param x A numerical vector of speed in knots
#'
#' @return A vector, speed in meters per second
#' @noRd
#' 
#' @author Einar Hjörleifsson, \email{einar.hjorleifsson@gmail.com}
#'
.rb_kn2ms <- function(x) {
  x / 1.94384449
}


#' rb_summarise_track
#'
#' @param d ...
#'
#' @return A summary tibble, dependent on grouping upstream
#' @export
#'
rb_summarise_track <- function(d) {
  d |> 
    dplyr::summarise(pings = dplyr::n(),
                     t.min = min(time),
                     t.max = max(time),
                     s.min = min(speed),
                     s.med = median(speed),
                     s.max = max(speed),
                     di.min = min(dist, na.rm = TRUE),
                     di.med = median(dist, na.rm = TRUE),
                     di.max = max(dist, na.rm = TRUE),
                     du.min = min(dura, na.rm = TRUE),
                     du.med = median(dura, na.rm = TRUE),
                     du.max = max(dura, na.rm = TRUE),
                     n.tips = dplyr::n_distinct(tid, na.rm = TRUE),
                     n.harb = dplyr::n_distinct(hid, na.rm = TRUE))
}


#' Pad harbour id
#' 
#' Add the harbour id to the first and the last point of an actual trip
#'
#' @param tid trip id, possibly generated by a rb_trip
#' @param hid harbour id
#'
#' @return The hid vector with added harbour id to the first and the last point
#' of a trip.
#' @export
#'
rb_pad_harbour <- function(tid, hid) {
  tibble::tibble(.tid = tid,
                 .hid = hid) |> 
    dplyr::mutate(.hid = dplyr::case_when(.tid !=  dplyr::lag(.tid) & .tid > 0 ~  dplyr::lag(.hid),
                                          .tid != dplyr::lead(.tid) & .tid > 0 ~ dplyr::lead(.hid),
                                          TRUE ~ .hid)) |> 
    dplyr::pull(.hid)
}


#' rb_peek
#' 
#' Experimental function, returns rows adjacent to the one fulfilling a critera
#'
#' @param d ais/vms track tibble
#' @param what the variable name to check
#' @param criteria the critera.
#'
#' @return a tibble
#' @export
#'
rb_peek <- function(d, what, criteria) {
  
  d |> 
    dplyr::filter( {{what}} > criteria) |> 
    dplyr::pull(.rid) ->
    rid
  d <-
    d |> 
    dplyr::mutate(whacky = ifelse(.rid %in% rid, "whacky", ""))
  # need to vectorize:
  rids <- NULL
  for(i in 1:length(rid)) rids <- c(rids, rid[i] + c(-2, -1, 0, 1, 2))
  d |> dplyr::filter(.rid %in% rids)
  
}

#' Convert speed between knots and metres per second
#'
#' @param x A numeric vector of speed.
#' @param from,to Units: `"kn"` (knots) or `"ms"` (metres per second).
#'
#' @return A numeric vector, speed in the `to` unit.
#' @export
#'
#' @examples
#' rb_convert_speed(0:8, from = "ms", to = "kn")
rb_convert_speed <- function(x, from = c("kn", "ms"), to = c("ms", "kn")) {
  from <- match.arg(from)
  to <- match.arg(to)
  if (from == to) return(x)
  if (from == "ms") .rb_ms2kn(x) else .rb_kn2ms(x)
}
